import test from 'node:test';import assert from 'node:assert/strict';
import {rooms,engine,review,callTool} from '../core.mjs';
import {validateBrief,inspectGenerated,generateDraft} from '../generation.mjs';
const copy=x=>JSON.parse(JSON.stringify(x));
const brief={topic:'Cybersecurity',audience:'Beginners',goal:'Reason from evidence',difficulty:'Beginner',locks:3};
test('correct answer alone cannot open an evidence-reasoning lock',()=>{const r=rooms[0],p=r.puzzles[0],s=engine.initial();p.required.forEach(id=>engine.inspect(s,p,id));assert.equal(engine.evaluate(r,s,p.answer,[]).kind,'reasoning');assert.equal(engine.evaluate(r,s,p.answer,p.evidence.map(e=>e.id)).kind,'reasoning');assert.equal(s.solved.length,0);assert.equal(engine.evaluate(r,s,p.answer,p.reasoning.evidenceIds).kind,'correct');});
test('review flags duplicate choices and never claims factual verification',()=>{const r=copy(rooms[0]);r.puzzles[0].options[1]=r.puzzles[0].options[0];const result=review.audit(r);assert.equal(result.publishable,false);assert.match(result.notice,/do not establish factual accuracy/);assert.ok(result.errors.length)});
test('learning plan, transfer and reasoning references are validated',()=>{const r=copy(rooms[0]);r.puzzles[0].reasoning.evidenceIds=['missing'];r.transfer.answer=99;r.learningPlan.prerequisites='not-an-array';assert.ok(engine.validate(r).length>=3)});
test('application-answer state survives reload without inventing success',()=>{const r=rooms[0],s=engine.initial();s.transferChoice=0;s.transferAttempts=1;const restored=engine.restore(r,s);assert.equal(restored.transferChoice,0);assert.equal(restored.transferAttempts,1);assert.notEqual(restored.transferChoice,r.transfer.answer)});
test('generation input and output are bounded and enforce requested depth',()=>{assert.equal(validateBrief(brief).locks,3);assert.throws(()=>validateBrief({...brief,locks:100}));assert.throws(()=>validateBrief({...brief,topic:''}));assert.equal(inspectGenerated(JSON.stringify(rooms[0]),brief).audit.errors.length,0);const weak=copy(rooms[0]);delete weak.transfer;assert.ok(inspectGenerated(JSON.stringify(weak),brief).audit.errors.length);assert.throws(()=>review.parse('Here is a room: {}'));});
test('review MCP tool runs deterministic checks',()=>{const result=callTool('review_room_draft',{room:copy(rooms[0])});assert.equal(result.publishable,true);assert.equal(result.checks.length,5)});
function fakeClient(outputs,models=[{name:'test/model'}]){let calls=0;return {get calls(){return calls},models:{list:async()=>({data:models})},mcpServers:{listTools:async()=>({data:[{name:'get_room_design_guide'},{name:'review_room_draft'}]})},sessions:{create:async()=>({data:{id:'synthetic-test-session'}}),createTurnStream:async()=>{const text=outputs[calls++];return {withMetadata:async function*(){yield {data:{type:'tool.response'}};yield {data:{type:'model.message.delta',content:text}};yield {data:{type:'turn.done',state:{status:'done'}}}}}}}};}
test('pipeline streams a valid draft only after independent validation (mocked model)',async()=>{const client=fakeClient([JSON.stringify(rooms[0])]),events=[];const result=await generateDraft(client,brief,e=>events.push(e));assert.equal(client.calls,1);assert.equal(result.audit.publishable,true);assert.equal(events.filter(e=>e.type==='draft').length,1);assert.ok(events.some(e=>e.type==='tool'));});
test('pipeline repairs malformed output once, then validates (mocked model)',async()=>{const client=fakeClient(['not-json',JSON.stringify(rooms[0])]),events=[];await generateDraft(client,brief,e=>events.push(e));assert.equal(client.calls,2);assert.ok(events.some(e=>e.message?.includes('one repair')))});
test('failed output is never published or emitted as a valid draft (mocked model)',async()=>{const events=[];await assert.rejects(()=>generateDraft(fakeClient(['invalid','invalid']),brief,e=>events.push(e)),/still needs repair/);assert.equal(events.some(e=>e.type==='draft'),false);await assert.rejects(()=>generateDraft(fakeClient([],[]),brief,()=>{}),/No model/)});
